import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import HeroHeader from "../components/Hero";

import {Container, Grid,} from "@mui/material";
import Header from "../components/AppBar";
import Footer from "../components/Footer";
import Markdown from "../components/Markdown";
// import {Recogniser} from "../recogniser";
export const getServerSideProps = async () => {
    // await Recogniser().catch(console.log);
    const markdown = await (await fetch("http://localhost:3000/dumps/markdown/pages/index.md")).text();

    return {
        props: {
            page_markdown: markdown
        }
    }
}
export default function Home({page_markdown}) {
    return (
        <div>
            <Container maxWidth="md">
                <Header/>
                <main>
                    <HeroHeader/>
                    <Grid container spacing={5} sx={{mt: 3}}>
                        <Grid
                            item
                            xs={12}
                            md={8}
                            sx={{
                                '& .markdown': {
                                    py: 3,
                                },
                            }}
                        >
                            <Markdown className="markdown">
                                {page_markdown}
                            </Markdown>
                        </Grid>
                        {/*<Sidebar/>*/}
                    </Grid>
                    {/*    <Main title="From the firehose" posts={posts} />*/}
                    {/*    <Sidebar*/}
                    {/*        title={sidebar.title}*/}
                    {/*        description={sidebar.description}*/}
                    {/*        archives={sidebar.archives}*/}
                    {/*        social={sidebar.social}*/}
                    {/*    />*/}
                    {/*</Grid>*/}
                </main>
            </Container>
            <Footer/>
            {/*    title="Footer"*/}
            {/*    description="Something here to give the footer a purpose!"*/}
            {/*/>*/}
        </div>
    )
}

function _Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Kabeer's Past Papers</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <Alert className={"mb-4"}
                       message="If you haven't figured it out yet, this project is in really early alpha, we are constantly adding stuff, check back to see fixed bugs and added features"
                       type="warning"/>
                <h1 className={styles.title}>
                    Kabeer's Past Papers
                </h1>

                <p className={styles.description}>
                    A Simpler yet smart Past Paper base.
                    <br/>
                    Our systems use AI to intelligently find helpful insight about papers, which lets you filter,
                    search, and arrange papers, mix and match topics
                    While our crawler goes around CAIE bases to look for more papers, we have put in place a yearly past
                    papers explorer with help from great people at `gceguide.com`
                </p>

                <div className={styles.grid}>
                    <a href="/ai" className={styles.card}>
                        <h2>Search &rarr;</h2>
                        <p>Query an ever increasing repository of pastpapers, our AI is always on extracting metadata,
                            text and images from papers.</p>
                    </a>

                    <a href="https://education.kabeersnetwork.tk/courses" className={styles.card}>
                        <h2>Courses &rarr;</h2>
                        <p>Introducing a new generation to Solving real world Problems through code.
                            Our classes are perfect beginners, amateurs, and even kids. We offer special group Calls and
                            video tutorial for better learning
                        </p>
                    </a>

                    <a
                        href="/yearly"
                        className={styles.card}
                    >
                        <h2>Yearly &rarr;</h2>
                        <p>Discover and explore a yearly paper repository, made possible by the help of awesome people
                            at gceguide.com</p>
                    </a>

                    <a
                        href="https://education.kabeersnetwork.tk/papers/Home/notes.html"
                        className={styles.card}
                    >
                        <h2>Books &rarr;</h2>
                        <p>
                            Find e-books notes and other resources
                        </p>
                    </a>
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
          </span>
                </a>
            </footer>
        </div>
    )
}
